### ISSUE TITLE
[Web Design] switch joystick out with separate Bulma-extension sliders for each axis

### ISSUE THREAD

**Issue by 2bndy5** [DVC-Viking-Robotics/webapp#29]
I would also like to have some kind of user customizability as to what each "remote controls" page contains. For instance: a button for braking, or a video display element to view camera feed.
- [x] Add [Bulma slider extension](https://wikiki.github.io/form/slider/)
- [x] alter controller.js to have a horizontal slider for the X-Axis & vertical slider for the Y-Axis

**Comment by tejashah88** [comment]
Resolved with #53
