### ISSUE TITLE
[Web design] Improve web app responsiveness

### ISSUE THREAD

**Issue by tejashah88** [DVC-Viking-Robotics/webapp#42]
Some of the web pages aren't optimized for mobile use and could use some CSS fine-tuning. 

Here's what the Autonomous Mode page shows: 
![image](https://user-images.githubusercontent.com/11187343/65854585-e5bf9d00-e311-11e9-97f1-f58dbf99fbf9.png)

**Comment by tejashah88** [comment]
FYI, the other pages display fairly well with the mobile view

**Comment by 2bndy5** [comment]
we should comment out [the sidebar](https://github.com/DVC-Viking-Robotics/webapp/blob/0cc6ff8c4ca211721e79083b4c9b12189f1f5a81/webapp/templates/layout.html#L56-L78) and [its hamburger button](https://github.com/DVC-Viking-Robotics/webapp/blob/0cc6ff8c4ca211721e79083b4c9b12189f1f5a81/webapp/templates/layout.html#L84-L86) until the user accounts/preferences and the remotes are re-done

**Comment by tejashah88** [comment]
Opened issue #45 for that. Until then, this issue has been addressed
