### ISSUE TITLE
[Web design] Comment out left sidebar and left hamburger button for now

### ISSUE THREAD

**Issue by tejashah88** [DVC-Viking-Robotics/webapp#45]
Quoting from @2bndy5 in #42

> we should comment out [the sidebar](https://github.com/DVC-Viking-Robotics/webapp/blob/0cc6ff8c4ca211721e79083b4c9b12189f1f5a81/webapp/templates/layout.html#L56-L78) and [its hamburger button](https://github.com/DVC-Viking-Robotics/webapp/blob/0cc6ff8c4ca211721e79083b4c9b12189f1f5a81/webapp/templates/layout.html#L84-L86) until the user accounts/preferences and the remotes are re-done

**Comment by FarhiaM** [comment]
Hi, is this issue still available? I would like to work on it? :)

**Comment by 2bndy5** [comment]
Oh sorry this has already been merged to master branch
